/*
 * ConsoleFrame.java
 *
 * Created on February 22, 2008, 12:29 AM
 */

package gui;

import cpu.Processor;
import java.util.Observable;
import java.util.Observer;

/**
 *
 * @author  Administrator
 */
public class ConsoleFrame extends javax.swing.JFrame implements Observer{
    
    
    /** Creates new form ConsoleFrame */
    public ConsoleFrame(Processor proc) 
    {
        this.proc = proc;
        
        initComponents();
        
    }
    public void printChar(char c)
    {
        
        jTextArea1.setText(jTextArea1.getText() + c);
        
        
    }
    public void update(Observable o1, Object o2)
    {
        
        char DDR = proc.mem[proc.DDR];
        char c = (char)(DDR & 0xff);
        if (DDR != 0)
        {
            printChar(DDR);
            proc.mem[proc.DDR] = 0;
        }
        proc.mem[proc.DSR] = 0x8000;
        
            
            
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Console");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName("consoleFrame"); // NOI18N

        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(60);
        jTextArea1.setEditable(false);
        jTextArea1.setFont(new java.awt.Font("Lucida Console", 1, 12));
        jTextArea1.setForeground(new java.awt.Color(204, 204, 204));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(20);
        jTextArea1.setCaretColor(new java.awt.Color(204, 204, 204));
        jTextArea1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextArea1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea1KeyTyped
        // TODO add your handling code here:
        proc.mem[proc.KSR] = 0x8000;
        proc.mem[proc.KDR] = evt.getKeyChar();
        printChar(evt.getKeyChar());
        
    }//GEN-LAST:event_jTextArea1KeyTyped
    
//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new ConsoleFrame(proc).setVisible(true);
//            }
//        });
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
    private Processor proc;
}
